apiVersion: v1
kind: Service
metadata:
  name: service-clusterip-subgraph-locations
  namespace: subgraph-app
spec:
  ports:
  - port: 4001
    protocol: TCP
    targetPort: 4001
  selector:
    type: subgraph-locations